feat: added pydantic models for Python
foundationopenresearch/ict-spec pull request #1
Opened 2023-08-17 05:59 UTC by camilovelezr

This PR:

- Creates a Python API
- Defines a Pydantic schema model based on [this spec](https://github.com/foundationopenresearch/ict-spec/blob/main/spec.md)

Examples:
```python3
import ict
my_example_ict_spec =  {
        "specVersion": "0.1.2",
        "name": "test/t2",
        "version": "0.1.0",
        "container": "wipp/wipp-backend:latest",
        "entrypoint": "test.py",
        "title": "Test Title",
        "description": "Test Description",
        "author": ["John Doe", "Jane Doe"],
        "contact": "c@u.edu",
        "repository": "https://github.com/ict",
        "citation": "10.5281/zenodo.1234",
        "inputs": [
            {
                "name": "foo",
                "type": "string",
                "description": "bar",
                "required": True,
                "format": ["es"],
            }
        ],
        "outputs": [
            {
                "name": "bar",
                "type": "array",
                "description": "bar",
                "required": "no",
                "format": ["es"],
            }
        ],
        "ui": [
            {
                "key": "inputs.foo",
                "title": "foo",
                "description": "bar",
                "type": "number",
                "condition": "inputs.foo==1",
            },
            {
                "key": "inputs.bar",
                "title": "foo",
                "description": "bar",
                "type": "text",
            },
        ],
    }
ict.validate(my_example_ict_spec)

ict.validate("/home/ict-user/my_awesome_ict.yml")
```

Running `ict.validate()` will perform validation and, if there are no errors, it will return an instance of `ICT`

2023-08-24 00:03 UTC, agerardin commented
Overall the code is very readable and well organized.


One remark :

- your example references spec 1.2, while the spec.md mention 1.0.
So it is not clear what is 1.2? The example you provide seems to vary slightly from the one in the repo. (ex for format, it is containing a single uri and term in 0.1.0 and it seems we have only list of string in 0.1.2 - I would guess we need a list of uri and term object).
- More generally, we probably need a versioning strategy for pydantic model because once the spec is in the wild, people will have different versions floating around.

One feature that may be needed :

- The tool seems to consume yaml. At least in compute we may also need to handle json but you may need to double-check that with the compute team.

The rest are comments for maintainability:

- Generally, i would recommend at least a few basic unit tests.
* At the api level, demonstrating that at least the canonical example for a version is run.
* as needed, for specific validation. that's really up to you but we make it easier for a maintainer to figure out the original intent, specially for regex
     ex:  the regex in check_container. My understanding is that no "_" are  allowed in registry path?

- If some parts of the model are coming from authoritative sources, we should provide a link.
ex : semver or w3date may or may not be, but that helps clarifying for the maintainer and maybe alleviate the need to write some more unit tests.

Those are all "extra-mile" considerations so feel free push to final review if needed.

2023-10-04 15:04 UTC, Nicholas-Schaub requested changes
Just a couple of minor changes, and this looks good to go. I am very impressed with it.

2023-10-04 15:04 UTC, Nicholas-Schaub commented on src/ict/hardware/objects.py
> +    """Return a string from int."""
If this is only supposed to be for `int`, we should add a check to make sure the input is an `int`.

If this should support `float`, we should update the type hint.

2023-10-04 15:04 UTC, Nicholas-Schaub commented on src/ict/io/objects.py
> +        + "represents using an ontology schema.",
Typo: repeated `represents`

2023-10-04 15:04 UTC, Nicholas-Schaub commented on src/ict/metadata/objects.py
> +            )
Could this be problematic for people of  non-western cultures?

2023-10-12 04:14 UTC, camilovelezr commented on src/ict/metadata/objects.py
> +            )
@sunnielyu @NHotaling

2024-01-08 17:06 UTC, merged